import { describe, it, expect, vi, beforeEach } from "vitest";
import { NextRequest } from "next/server";

// The login endpoint is the only public, unauthenticated path that accepts a
// credential. Before this it had no throttle at all, so a passcode could be
// ground down at whatever rate the network allowed.

const findUniqueMock = vi.fn();
const upsertMock = vi.fn();

vi.mock("@/lib/db", () => ({
  db: {
    rateLimit: {
      findUnique: (...a: unknown[]) => findUniqueMock(...a),
      upsert: (...a: unknown[]) => upsertMock(...a),
    },
  },
}));

function login(passcode: unknown) {
  return new NextRequest("http://localhost:3000/api/admin/login", {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-real-ip": "203.0.113.7" },
    body: JSON.stringify({ passcode }),
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  vi.resetModules();
  findUniqueMock.mockResolvedValue(null);
  upsertMock.mockResolvedValue({});
  process.env.ADMIN_USERS = "Alex:pass-alex-2026";
});

describe("POST /api/admin/login", () => {
  it("accepts the right passcode and sets a session cookie", async () => {
    const { POST } = await import("@/app/api/admin/login/route");
    const res = await POST(login("pass-alex-2026"));
    expect(res.status).toBe(200);

    const cookie = res.cookies.get("wave_admin");
    expect(cookie?.value.startsWith("v1.")).toBe(true);
    // The cookie must not be the credential any more.
    expect(cookie?.value).not.toContain("pass-alex-2026");
    expect(cookie?.httpOnly).toBe(true);
    expect(cookie?.sameSite).toBe("strict");
    // And it must not outlive the token inside it.
    expect(cookie?.maxAge).toBe(12 * 60 * 60);
  });

  it("rejects a wrong passcode with no hint about why", async () => {
    const { POST } = await import("@/app/api/admin/login/route");
    const res = await POST(login("not-it"));
    expect(res.status).toBe(401);
    expect((await res.json()).error).toBe("Incorrect passcode.");
    expect(res.cookies.get("wave_admin")).toBeUndefined();
  });

  it("gives the same answer for an unknown user as a wrong passcode", async () => {
    // Different messages would tell a guesser which half they got right.
    const { POST } = await import("@/app/api/admin/login/route");
    const wrong = await POST(login("not-it"));
    const empty = await POST(login(""));
    expect(await wrong.json()).toEqual(await empty.json());
    expect(wrong.status).toBe(empty.status);
  });

  it("throttles repeated attempts on its own bucket", async () => {
    const { POST } = await import("@/app/api/admin/login/route");
    await POST(login("guess"));
    const key = findUniqueMock.mock.calls.at(-1)![0].where.key as string;
    expect(key.startsWith("admin-login:")).toBe(true);
  });

  it("refuses once the attempt limit is spent", async () => {
    findUniqueMock.mockResolvedValue({ count: 10, windowStart: new Date() });
    const { POST } = await import("@/app/api/admin/login/route");
    // Correct passcode, but the quota is gone: throttling must apply before
    // the credential is even looked at.
    const res = await POST(login("pass-alex-2026"));
    expect(res.status).toBe(429);
    expect(res.headers.get("Retry-After")).toBeTruthy();
    expect(res.cookies.get("wave_admin")).toBeUndefined();
  });

  it("DENIES when the throttle store is down, rather than waving through", async () => {
    // The opposite of /api/submit's fail-open, and deliberately so: an
    // unthrottled login is unlimited guessing.
    findUniqueMock.mockRejectedValue(new Error("db down"));
    const { POST } = await import("@/app/api/admin/login/route");
    const res = await POST(login("pass-alex-2026"));
    expect(res.status).toBe(429);
  });

  it("accepts a hashed passcode and still never echoes it", async () => {
    // Generated by scripts/hash-admin-passcode.ts for "a-test-passcode-123".
    process.env.ADMIN_USERS =
      "Ben:scrypt$65536$8$1$r1HeLpwlVTt8y6YTl3hrdA==$TelW8+DpPDI23w7ieV45zcfc9BArXBDA7/dEiN9bS8g=";
    const { POST } = await import("@/app/api/admin/login/route");

    const good = await POST(login("a-test-passcode-123"));
    expect(good.status).toBe(200);
    expect(good.cookies.get("wave_admin")?.value.startsWith("v1.")).toBe(true);

    const bad = await POST(login("a-test-passcode-124"));
    expect(bad.status).toBe(401);
  }, 20000);

  it("rejects everything when ADMIN_USERS is unset, rather than opening up", async () => {
    delete process.env.ADMIN_USERS;
    const { POST } = await import("@/app/api/admin/login/route");
    expect((await POST(login("anything"))).status).toBe(401);
  });
});
